### ISSUE TITLE
Currency is not shown up in the serializer field and then unable to save an instance

### ISSUE THREAD

**Issue by elcolie** [django-money/django-money#351]
django-money==0.12
Django==1.11.7
py-moneyed==0.7.0

I have `djmoney` in the `settings.py` already.

**models.py**:
```python
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from djmoney.models.fields import MoneyField

from poinkbackend.apps.activities.models import Activity
from poinkbackend.apps.branches.models import Branch
from poinkbackend.apps.commons.models import AbstractTimestamp


class Order(AbstractTimestamp):
    poink = models.PositiveIntegerField()
    amount = MoneyField(max_digits=10, decimal_places=2, default_currency='THB')
    cashier = models.ForeignKey(User, related_name='orders', on_delete=models.PROTECT)
    branch = models.ForeignKey(Branch, related_name='orders', on_delete=models.PROTECT, null=True, blank=True)

    activities = GenericRelation(Activity, related_query_name='orders', related_name='orders')

    def __str__(self):
        return f'{self.amount.value}'

```

**serializers.py**:
```python
import logging

from django.contrib.auth.models import User
from rest_framework import serializers

from poinkbackend.apps.commons.serializers import MoneyField, MyMoneyField
from poinkbackend.apps.orders.models import Order

logger = logging.getLogger('django')


class OrderSerializer(serializers.ModelSerializer):
    customer = serializers.PrimaryKeyRelatedField(queryset=User.objects.all())

    class Meta:
        model = Order
        fields = [
            'poink',
            'amount',
            'customer',
            'cashier',
            'branch',
        ]

    def validate_customer(self, attrs):
        logger.info(f'---->{attrs}')
        return attrs


    def save(self, **kwargs):
        logger.info(f'---->{kwargs}')
        return None

```

No currency show up here
![screen shot 2560-11-16 at 10 08 38](https://user-images.githubusercontent.com/18206728/32871878-2eeab1ca-cab6-11e7-9c33-d067eb2dcdf7.png)

**Error When Save:**
```bash
127.0.0.1 - - [16/Nov/2017 03:10:24] "POST /api/orders/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/sarit/.pyenv/versions/3.6.3/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/rest_framework/viewsets.py", line 90, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/rest_framework/mixins.py", line 22, in create
    headers = self.get_success_headers(serializer.data)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/rest_framework/serializers.py", line 533, in data
    ret = super(Serializer, self).data
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/rest_framework/serializers.py", line 264, in data
    self._data = self.to_representation(self.validated_data)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/rest_framework/serializers.py", line 500, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/Users/sarit/.pyenv/versions/3.6.3/envs/poink/lib/python3.6/site-packages/djmoney/contrib/django_rest_framework/fields.py", line 16, in to_representation
    return super(MoneyField, self).to_representation(obj.amount)
AttributeError: 'decimal.Decimal' object has no attribute 'amount'
```

**Comment by elcolie** [comment]
Right now I do workaround by hardcoding the `currency`.
Anything I missing please let me know.

```python
from djmoney.contrib.django_rest_framework import MoneyField
from moneyed import Money, Decimal


class MyMoneyField(MoneyField):
    def to_representation(self, obj):
        return {
            'amount': "%f" % (obj.amount),
            'currency': "%s" % (obj.currency),
        }

    def to_internal_value(self, data):
        return Money(Decimal(data), 'THB')
```

**Comment by Stranger6667** [comment]
Hello!
It is a bug in djmoney. It occurs when only `money` is specified in serializer's ``Meta.fields`` without `money_currency`. I'll submit a fix on Monday

**Comment by Stranger6667** [comment]
The issue is fixed in the master branch.

**Comment by elcolie** [comment]
> It is a bug in djmoney. It occurs when only money is specified in serializer's Meta.fields without money_currency. I'll submit a fix on Monday

My timezone is Monday now :)

**Comment by benjaoming** [comment]
@elcolie and the fix landed 3 days ago

**Comment by elcolie** [comment]
No no. I mean did you send the issue to `djmoney`?
I haven't seen any reverse issue in the github to this issue from `djmoney`

**Comment by benjaoming** [comment]
This *is* `djmoney` - `djmoney` is the name of the package that `django-money` installs.

**Comment by Abishek05** [comment]
Currency is still not showing up in the serializer field. I am using `py-moneyed==0.8.0` and `django-money==1.1` Am I missing something?

Even after specifying the price_currency field in the serializer meta class, it doesn't show.

**models.py**

```
class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    price = MoneyField(max_digits=14, decimal_places=2)
```

**serializers.py**

```
class ProductSerializer(serializers.ModelSerializer):
    """serializer for Product objects."""

    class Meta:
        model = models.Product
        fields = ('id', 'name', 'price', 'price_currency', )
```
