### ISSUE TITLE
Implicit type conversion to Decimal in multiplication and raising TypeError in addition breaks commutativity for non-standard numeric types

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [django-money/django-money#606]
`__mul__` implicitly attempts to cast the right operand as `Decimal` by passing its string representation to the constructor.
This type cast is unexpected and breaks commutativity for multiplication in cases where the right operand also defines its own `__mul__`. 

Additionally, a number of types may have a string representation that is convertible by Decimal, but which would not create the correct value, such as percentages. Even if it's not convertible, rather than returning a `NotImplemented` and calling `__rmul__` on the right operand, it will raise a `Decimal.ConversionSyntax` error, thus ultimately requiring you to swap the left and right operand in order to force the correct `__mul__` to be called, thus breaking commutativity for multiplication as stated.

A similar issue occurs with addition and subtraction, where it will raise a `TypeError` for non-standard numeric types, thus preventing `__radd__` from being called on the right operand, which may in fact define a value for Money instances and also breaking commutativity.

I suggest to either manually call `__radd__`/`__rmul__` of rhs or to return `NotImplemented` to signal Python to do so for you, thus requiring non-standard types to either explicitly be converted into `Decimal` or define the operation for Money instances.

**Comment by benjaoming** [comment]
Hi @DeltaEpsilon7787 👋 

If you are able to work out a test showing the error and a patch fixing it, I am sure that the fix can find its way.

A slightly similar issue was fixed recently, it can be a good recipe for an approach of test+fix: https://github.com/django-money/django-money/pull/594

**Comment by DeltaEpsilon7787** [comment]
Looking more into it, I have discovered this issue happens in moneyed library whereas django-money inherits it.

The issue was fixed for `__add__` operations with this https://github.com/py-moneyed/py-moneyed/pull/152, however `__mul__` is still incorrect.

I will close this issue for this repo.
