### ISSUE TITLE
Could not resolve manager type for "core.models.FooModel.objects" [django-manager-missing]

### ISSUE THREAD

**Issue by MartinThoma** [django-money/django-money#677]
When I use django-money==3.0.0 and django-stubs==1.12.0 and django-stubs-ext==0.5.0, mypy complains:

> Could not resolve manager type for "core.models.FooModel.objects" [django-manager-missing]

According to https://github.com/typeddjango/django-stubs/issues/1023 . A user mentioned that django-money should export types.

I'm not sure what that means and I haven't seen an issue here about this topic. Do you know the issue?

**Comment by flaeppe** [comment]
Related to: https://github.com/django-money/django-money/issues/674#issuecomment-1153121644

**Comment by aleksanb** [comment]
https://github.com/django-money/django-money/blob/8ce85afd51f238a9f1793d9de1ffee4d299191fe/djmoney/models/managers.py#L226
Here is where the manager is dynamically generated. We should be able to declare it statically, perhaps?

**Comment by sondrelg** [comment]
I think "export types" is referring to adding a `py.typed` to the repo (see [PEP](https://peps.python.org/pep-0561/)), telling mypy that it can use exported types from the library when type checking. So, unless I'm wrong, adding a `py.typed` is the main thing missing; and then adding better type hints to the library itself will make the general experience better 👍

**Comment by sondrelg** [comment]
Anyone working on this? I might open a PR this week otherwise

**Comment by benjaoming** [comment]
@sondrelg It should be mentioned that someone wanted to start an approach with .pyi files: https://github.com/django-money/django-money/pull/686

How can all this type stuff be done in just a single place so we don't end up with 3 different definitions?

I haven't worked with type hints in a reusable application before, but if you do add them, I would also raise this question: Is there a linting mechanism that can safe-guard that it's correctly applied in future contributions? We already use pre-commit and [apply it in CI](https://github.com/django-money/django-money/blob/main/tox.ini#L30) in the Tox linting step. If you can contribute what you need and safe-guard that the same standard is followed through a linter, then I think we're in good shape :+1:

**Comment by sondrelg** [comment]
@karolyi any reason you prefer stubs over inline annotations? :slightly_smiling_face: I don't really mind, but my impression is that stubs are harder to maintain. 

> I haven't worked with type hints in a reusable application before, but if you do add them, I would also raise this question: Is there a linting mechanism that can safe-guard that it's correctly applied in future contributions? 

Yep, it's trivial to run mypy or pyright using pre-commit, so I think adding that there would be simple :+1:  Look at [this](https://github.com/snok/asgi-correlation-id/blob/main/.github/workflows/test.yml#L9:L23) for an example of how you might run it in CI. I haven't looked at this project's CI yet though, so maybe another approach is better, but either way it should be no problem :slightly_smiling_face: 

So adding type hints is great, and then we need to add a `py.typed` to the djmoney directory - that's really what exporting types is referring to. And then I think this should be resolved :+1:

**Comment by karolyi** [comment]
I'm using pyright in my projects (after trying pylsp and mypy, I needed something faster), and pyright had issues with differentiating various input and output types on the `__add__`, `__mul__` and other operator functions, mostly because of the complexity of the original code, that also uses inheritance from django fields.

Pyright says that it's only going to dive so deep into code recursion to come up with the right return type in order to keep up its fastness, so I personally needed to come up with a solution that would solve the input-output type coherence.

Ever since I added my typing to the project (the same I made the pull request with), the typing works without issues.

Not sure if this is an argument for you, but it covered my use case just right.

**Comment by sondrelg** [comment]
Given this code

```python
# main.py

def main(a, b):
    return a + b
```

When adding type hints to a project you have 2 choices. You could add a stubs file like this:

```python
# main.pyi

def main(a: int, b: int) -> int: ...
```

Or you can add types into the original file, directly, like this:

```python
# main.py

def main(a: int, b: int) -> int:
    return a + b
```

Both approaches will fix this issue, but with the second approach you end up with a new separate file that has to track the changes made to the library at all times. It's very easy for drift to happen, and inline types are informative so make it easier to read the code, in my opinion.

What I was trying to ask is whether there was a good reason why you chose the first option instead of the second? :slightly_smiling_face:

**Comment by sondrelg** [comment]
If not, then perhaps I could take a stab at adding inline types instead :+1:

**Comment by karolyi** [comment]
@sondrelg if you've posed the question at me, yes it was exactly the reason why I needed to add the separate file, because the code itself wasn't explicit enough about the input-output types. Here's the actual example:

```python
    @overload
    def __add__(self, other: Money) -> Money: ...
    @overload
    def __add__(self, other: F) -> CombinedExpression: ...
    @overload
```

If you look at the actual code behind these type definitions, you'll see that in the case of an `F` passed, the code starts to evaluate the result differently:

```python
def __add__(self, other):
        if isinstance(other, F):
            return other.__radd__(self)
        other = maybe_convert(other, self.currency)
        result = super().__add__(other)
        self._copy_attributes(other, result)
        return result
```

Because of the aforementioned reasons, the return type wasn't crystal clear (couldn't be clearly inferred) for pyright. Same goes with the case of non-`F` expressions.

Hope this clears things up from my side.

**Comment by sondrelg** [comment]
Yes that makes sense. Just so you know, you can add overload type hints into the same file as well. You don't have to add it to a `.pyi` file.

You could do it like this:

```python
from typing import overload


@overload 
def main(a: int, b: int) -> int: ...

@overload 
def main(a: float, b: float) -> float: ...

def main(a: int | float, b: int | float) -> int | float:
    return a + b
```
directly in the code

I think I'll do this :+1:

**Comment by karolyi** [comment]
Yes I knew it but I didn't want to 'muddle up' the code with type definitions. Feel free to do whatever works for you, as long as it works for me too :) I'll let you know if it doesn't anyway, over time :)

**Comment by benjaoming** [comment]
Can `.pyi` files be auto-generated and maintained as assets if inline types are used?

**Comment by karolyi** [comment]
AFAIK `.pyi` stubs can be generated from code, to be adjusted/maintained by hand later on. I think I even did that when coming up with my MR.

It might well be that the final stubs are capable to be generated as well, if the original code contains them. Haven't tested that though, and it also feels kinda a duplication.

**Comment by benjaoming** [comment]
The idea of auto-generating `.pyi` and maintaining them as artifacts would be that we avoid duplication and instead have a single source of truth, i.e. the inline type hints.

**Comment by sondrelg** [comment]
> The idea of auto-generating `.pyi` and maintaining them as artifacts would be that we avoid duplication and instead have a single source of truth, i.e. the inline type hints.

You don't need pyi files at all @benjaoming. You can have inline types and nothing else

**Comment by benjaoming** [comment]
@sondrelg yes, I would also think that it make sense to create type hints inline and find a way to generate .pyi files from there on, if there is a need. I believe that @karolyi is advocating exactly that this need exists because of the performance of static type checkers etc.

**Comment by karolyi** [comment]
@benjaoming  Yes, that would be one argument.

**Comment by sondrelg** [comment]
Sorry I don't get it. Which static type checkers perform better if there are stubs available? I've never heard that before - do you have any documentation that states that?

**Comment by karolyi** [comment]
see https://github.com/microsoft/pyright/blob/main/docs/type-stubs.md

**Comment by sondrelg** [comment]
> it’s highly recommended that you consume “py.typed” packages or use type stub files for all external imports

This is the same as mypy. Essentially, py.typed + inline types are all you need, is how I'm reading this :thinking:

**Comment by karolyi** [comment]
> Imported libraries can be quite large, so analyzing them can require significant time and computation.

This would be the gist of it to me. Again, feel free to do whatever you want as long as it works, but if you're really going for speed, the typing stubs are the way to go. Generated or maintained by hand, doesn't matter.

**Comment by benjaoming** [comment]
Should #686 be closed? Has this issue been fixed by https://github.com/django-money/django-money/pull/691?

**Comment by sebastian-philipp** [comment]
still getting the same error: 

```
$ pip install django-money==3.3.0
Collecting django-money==3.3.0
  Obtaining dependency information for django-money==3.3.0 from https://files.pythonhosted.org/packages/4e/9c/480548bb4d773cb2e01c485593b4bff6230cf262107d9e44028ea28da668/django_money-3.3.0-py3-none-any.whl.metadata
... snip...
$ mypy
pricing/models.py: note: In class "Pricing":
pricing/models.py:71: error: Could not resolve manager type for "pricing.models.Pricing.objects"  [django-manager-missing]
```

**Comment by benjaoming** [comment]
@sebastian-philipp interesting - could it be that these observations need to be followed? https://github.com/jsvine/pdfplumber/issues/698#issuecomment-1205272378

**Comment by sebastian-philipp** [comment]
```
$ pip install django-money==3.3.0
$ ll venv/lib/python3.10/site-packages/djmoney 
insgesamt 56K
-rw-r--r--. 1 sebastian sebastian  644 16. Okt 13:16 admin.py
-rw-r--r--. 1 sebastian sebastian  426 16. Okt 13:16 apps.py
-rw-r--r--. 1 sebastian sebastian  564 16. Okt 13:16 _compat.py
drwxr-xr-x. 5 sebastian sebastian 4,0K 16. Okt 13:16 contrib
drwxr-xr-x. 3 sebastian sebastian 4,0K 16. Okt 13:16 forms
-rw-r--r--. 1 sebastian sebastian  247 16. Okt 13:16 __init__.py
drwxr-xr-x. 3 sebastian sebastian 4,0K 16. Okt 13:16 models
-rw-r--r--. 1 sebastian sebastian 5,6K 16. Okt 13:16 money.py
drwxr-xr-x. 2 sebastian sebastian 4,0K 16. Okt 13:16 __pycache__
-rw-r--r--. 1 sebastian sebastian 2,4K 16. Okt 13:16 serializers.py
-rw-r--r--. 1 sebastian sebastian 1,7K 16. Okt 13:16 settings.py
drwxr-xr-x. 3 sebastian sebastian 4,0K 16. Okt 13:16 templatetags
-rw-r--r--. 1 sebastian sebastian 1,1K 16. Okt 13:16 utils.py
$ mypy 
...snip...
error: Skipping analyzing "djmoney": module is installed, but missing library stubs or py.typed marker  [import]
error: Could not resolve manager type for "pricing_engine.models.new.Pricing.objects"  [django-manager-missing]
...snip...
$ touch  venv/lib/python3.10/site-packages/djmoney/py.typed
$ mypy 
error: Could not resolve manager type for "pricing_engine.models.new.Pricing.objects"  [django-manager-missing]
```

3.3.0 still misses the py.typed file, but unfortunately it doesn't fix the django-manager issue. But I feel we're getting there.

**Comment by sebastian-philipp** [comment]
https://github.com/typeddjango/django-stubs/blob/fd0d77164bb3b39bfd319f9d922d3a73c0aab721/mypy_django_plugin/transformers/models.py#L114-L123

**Comment by benjaoming** [comment]
> Yes, 3.3.0 still misses the py.typed file, but unfortunately it doesn't fix the django-manager issue. But I feel we're getting there.

PRs fixing this welcome :+1:

**Comment by flaeppe** [comment]
@sebastian-philipp I think this https://github.com/django-money/django-money/issues/677#issuecomment-1167436929 is still the "conclusion"?

Also, that can be verified by looking at the runtime type of the manager. e.g.

```python
class SomeModel(models.Model):
    ...

print(type(SomeModel.objects))
```

**Comment by sebastian-philipp** [comment]
> @sebastian-philipp I think this https://github.com/django-money/django-money/issues/677#issuecomment-1167436929 is still the "conclusion"?

I think so!
